package edu.npu.courseapp.test.dao;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import edu.npu.courseapp.dao.StudentDao;
import edu.npu.courseapp.domain.Gender;
import edu.npu.courseapp.domain.Student;

/* NOTE: This is testing the StudentDao only, not the web application.   Make sure the server is not running, we are
 * testing this independent of the web application.   Also make sure you have added a Student to the database using
 * addSampleData.sql (resources folder).
 */
@ContextConfiguration("classpath:courseapp-test-context.xml")
@RunWith(SpringJUnit4ClassRunner.class)
public class StudentDaoTest {
	@Autowired
	@Qualifier("StudentDaoJdbcImpl")
	private StudentDao studentDao;
	private Student studToLookup;
	
	@Before
	public void init() {
		studToLookup = new Student(); 
		studToLookup.setLastName("Jefferson");
		studToLookup.setFirstName("Bill");
		studToLookup.setAge(23);
		studToLookup.setGender(Gender.Male);
		studToLookup.setId(1);
	}
	
	@Test
	public void testFindStudentWithId() {
		int testId = 1;
		Student retrievedStud = studentDao.findStudentFromId(testId);
		assertEquals(retrievedStud,studToLookup);
	}
	
	@Test
	public void testInsertStudent() {
		Student studToInsert;
		studToInsert = new Student(); 
		studToInsert.setLastName("Borello");
		studToInsert.setFirstName("Jennifer");
		studToInsert.setAge(27);
		studToInsert.setGender(Gender.Female);
		long idOfInsertedStud;
		
		studentDao.insertStudent(studToInsert);
		idOfInsertedStud = studToInsert.getId(); /* id assignment is a side effect of insertStudent()  */
		assertTrue(idOfInsertedStud > 0);   /* Should have been given an id -- autogenerated by database */
		
		Student retrievedStud = studentDao.findStudentFromId(idOfInsertedStud);
		assertEquals(retrievedStud,studToInsert);
	}
}